### ISSUE TITLE
Version 5.2.2.4286: typo in /usr/local/munki/munkilib/prefs.py line 310  

### ISSUE THREAD

**Issue by ryansumma** [munki/munki#1078]
in version 5.2.2.4286

`sudo managedsoftwareupdate --show-config` 

throws error:

`Current Munki configuration:
                   AdditionalHttpHeaders:  None [not set]
        AggressiveUpdateNotificationDays:    14 [/Library/Preferences/ManagedInstalls.plist]
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1218, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 689, in main
    prefs.print_config()
  File "/usr/local/munki/munkilib/prefs.py", line 310, in print_config
    value = false
NameError: name 'false' is not defined`

changing 'false' to 'False' solves issue

**Comment by gregneagle** [comment]
Same as https://github.com/munki/munki/pull/1074
