### ISSUE TITLE
Munki can attempt to install software even if all dependancies are not met

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1104]
We got some reports of a few machines where managedsoftwareupdate was broken:

```
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 59, in <module>
    from munkilib import appleupdates
  File "/usr/local/munki/munkilib/appleupdates/__init__.py", line 5, in <module>
    from .core import *
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 23, in <module>
    from . import au
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 46, in <module>
    from . import sync
  File "/usr/local/munki/munkilib/appleupdates/sync.py", line 56, in <module>
    from .. import fetch
  File "/usr/local/munki/munkilib/fetch.py", line 64, in <module>
    from .gurl import Gurl
  File "/usr/local/munki/munkilib/gurl.py", line 73, in <module>
    from asn1crypto.x509 import Certificate, Name
ModuleNotFoundError: No module named 'asn1crypto'
```

Reinstalling Munki's Python subpackage from the 5.5 release fixed things. But this implied that the core tools had been updated to Munki 5.5 without also updating the Python framework at the same time. I wanted to understand why that happened.

From `/Library/Managed Installs/Logs/Install.log`:

```
Jun 09 2021 08:58:06 -0700 Install of <unrelated thing>: SUCCESSFUL
Jun 10 2021 07:52:10 -0700 Install of Managed Software Center core tools-5.5.0.4360: SUCCESSFUL
Jun 10 2021 07:52:13 -0700 Install of Managed Software Center admin tools-5.5.0.4360: SUCCESSFUL
Jun 10 2021 07:52:18 -0700 Install of Managed Software Center app usage-5.5.0.4360: SUCCESSFUL
Jun 10 2021 07:53:09 -0700 Install of <unrelated thing>: SUCCESSFUL
```

So clearly Munki did upgrade the Munki tools to the 5.5 release without also upgrading the Python. (it also did not upgrade the GUI apps, which is a clue, but not a cause of the issue)

Looking at the ManagedSoftwareUpdate.log:
```
Jun 10 2021 07:51:04 -0700     munkitools-5.4.0.4362 requires munkitools_python. Getting info on munkitools_python...
Jun 10 2021 07:51:04 -0700     Need to install munkitools_python
Jun 10 2021 07:51:04 -0700     Downloading munkitools_python-3.9.5.4361.pkg from munkitools/munkitools_python-3.9.5.4361.pkg
Jun 10 2021 07:51:04 -0700     Downloading munkitools_python-3.9.5.4361.pkg from munkitools/munkitools_python-3.9.5.4361.pkg
Jun 10 2021 07:51:04 -0700     Downloading munkitools_python-3.9.5.4361.pkg...
Jun 10 2021 07:51:04 -0700     Bytes received: 319
Jun 10 2021 07:51:04 -0700 WARNING: Download of munkitools_python failed: HTTP result 404: not found
Jun 10 2021 07:51:04 -0700     munkitools-5.4.0.4362 requires munkitools_core. Getting info on munkitools_core...
Jun 10 2021 07:51:04 -0700     munkitools_core-5.5.0.4360 requires munkitools_python. Getting info on munkitools_python...
Jun 10 2021 07:51:04 -0700     munkitools_core-5.5.0.4360 requires munkitools_launchd. Getting info on munkitools_launchd...
Jun 10 2021 07:51:04 -0700     munkitools_launchd version 3.0.3265 (or newer) is already installed.
Jun 10 2021 07:51:04 -0700     Need to install munkitools_core
Jun 10 2021 07:51:04 -0700     Downloading munkitools_core-5.5.0.4360.pkg from munkitools/munkitools_core-5.5.0.4360.pkg
Jun 10 2021 07:51:04 -0700     Downloading munkitools_core-5.5.0.4360.pkg from munkitools/munkitools_core-5.5.0.4360.pkg
Jun 10 2021 07:51:05 -0700     Downloading munkitools_core-5.5.0.4360.pkg...
Jun 10 2021 07:51:05 -0700     Verifying package integrity...
Jun 10 2021 07:51:06 -0700     Need to install munkitools_admin
Jun 10 2021 07:51:06 -0700     Downloading munkitools_admin-5.5.0.4360.pkg from munkitools/munkitools_admin-5.5.0.4360.pkg
Jun 10 2021 07:51:06 -0700     Downloading munkitools_admin-5.5.0.4360.pkg from munkitools/munkitools_admin-5.5.0.4360.pkg
Jun 10 2021 07:51:06 -0700     Downloading munkitools_admin-5.5.0.4360.pkg...
Jun 10 2021 07:51:06 -0700     Verifying package integrity...
Jun 10 2021 07:51:06 -0700     munkitools-5.4.0.4362 requires munkitools_launchd. Getting info on munkitools_launchd...
Jun 10 2021 07:51:06 -0700 WARNING: Didn't attempt to install munkitools because could not resolve all dependencies.
```

So downloading the Python pkg failed, and Munki _appears_ here to do the right thing and decides not to install `munkitools`. But then:
```
Jun 10 2021 07:51:06 -0700     munkitools_app_usage-5.5.0.4360 requires munkitools_python. Getting info on munkitools_python...
Jun 10 2021 07:51:06 -0700     munkitools_app_usage-5.5.0.4360 requires munkitools_core. Getting info on munkitools_core...
Jun 10 2021 07:51:06 -0700     munkitools_app_usage-5.5.0.4360 requires munkitools_launchd. Getting info on munkitools_launchd...
Jun 10 2021 07:51:06 -0700     Need to install munkitools_app_usage
Jun 10 2021 07:51:06 -0700     Downloading munkitools_app_usage-5.5.0.4360.pkg from munkitools/munkitools_app_usage-5.5.0.4360.pkg
Jun 10 2021 07:51:06 -0700     Downloading munkitools_app_usage-5.5.0.4360.pkg from munkitools/munkitools_app_usage-5.5.0.4360.pkg
Jun 10 2021 07:51:07 -0700     Downloading munkitools_app_usage-5.5.0.4360.pkg...
```
There's a logic/behavior flaw here. Somehow when processing `munkitools_app_usage` it fails to notice that it doesn't have the python part, and since `munkitools_app_usage` requires `munkitools_core`, munkitools_core gets installed. The python install doesn't happen, and now we have a broken Munki.

We need to figure out why the check for `munkitools_python` passed the second time, even though the download of the pkg failed.

**Comment by gregneagle** [comment]
(and yes, this machine has been broken for over two months. :-( )

**Comment by gregneagle** [comment]
Attempt to address the issue here: https://github.com/munki/munki/commit/0cd2f6875a727ab995868c34488536e620ea6343

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/9ba39afe2bf5fb2d0384681b6d56be0872bc6d36
