### ISSUE TITLE
MunkiImport fails on latest version with "ImportError: Framework CoreServices could not be found"

### ISSUE THREAD

**Issue by zenopopovici** [munki/munki#1121]
Munki 5.6.2 crashes when trying to import packages. This doesn't happen with 5.6.1

```bash
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 16, in __init__
    from munkilib.admin import munkiimportlib
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 34, in <module>
    from .. import osinstaller
  File "/usr/local/munki/munkilib/osinstaller.py", line 47, in <module>
    from . import info
  File "/usr/local/munki/munkilib/info.py", line 37, in <module>
    import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 18, in <module>
    "/System/Library/Frameworks/CoreServices.framework/CoreServices"
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 136, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 130, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 98, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 292, in main
    self.env["force_munki_repo_lib"],
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 168, in _fetch_repo_library
    munki_repo, munki_repo_plugin, munkilib_dir, repo_subdirectory
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 20, in __init__
    f"munkilib import error: {str(err)}\nMunki tools version 3.2.0.3462 or "
autopkglib.ProcessorError: munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
Failed.
Receipt written to /Users/Zeno/Library/AutoPkg/Cache/com.graffino.autopkg.munki.fig/receipts/Fig.munki-receipt-20211115-174902.plist

The following recipes failed:
    Fig.munki.recipe
        Error in com.graffino.autopkg.munki.fig: Processor: MunkiImporter: Error: munkilib import error: Framework CoreServices could not be found
        Munki tools version 3.2.0.3462 or later is required.
```

**Comment by gregneagle** [comment]
This appears to be an Autopkg error.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/issues/999
AutoPkg will need to update the included version of PyObjC (assuming you are running current AutoPkg)

**Comment by zenopopovici** [comment]
@gregneagle I'm sorry I'm being persistent but this worked perfectly in 5.6.1 if a breaking change was introduced in 5.6.2 shouldn't this be a major version release? I'm using the latest version of autopkg.

**Comment by nmcspadden** [comment]
Following up on https://github.com/autopkg/autopkg/issues/701, this doesn't seem to be a problem with AutoPkg - I am unable to reproduce this interaction at all.

**Comment by gregneagle** [comment]
@zenopopovici Your report doesn’t involve the Munki tools at all. You are encountering a problem while running _Autopkg_.  The traceback references Autopkg’s Python framework. If this is a real issue, it is an Autopkg issue. 

Nick cannot reproduce the issue. So until there is a way to reproduce this issue, it’s unlikely any progress will be made on it.
