### ISSUE TITLE
MunkiImport fails on latest version with "ImportError: Framework CoreServices could not be found" #1121

### ISSUE THREAD

**Issue by zenopopovici** [munki/munki#1127]
Hello,

I'm following up to: https://github.com/munki/munki/issues/1121 and https://github.com/autopkg/autopkg/issues/775

I've tried this on a fresh installed system. I would greatly appreciate any help, this bug would prevent anyone with an M1 machine to run AutoPKG to update Munki.

## System configuration
1. MacBook Pro M1 16GB RAM
2. macOS 12.2 (21D49)

## Packages installed
1. `autopkg-2.3.1.pkg`
2. `munkitools-5.6.3.4401.pkg`
3.  XCode Developer Tools
4. Rosetta (it seems AutoPKG won't run without Rosetta).
5. Copied a simple Munki recipe

## Affected Munki versions:
- >=5.6.2 
-  v5.6.1 does not have this issue. 

## Tested also on MacBook Pro with Intel (same fresh install)
- does not have this issue.

I tried debugging the issue, however, my knowledge of Python is limited.  I'm guessing this is happening because of the inclusion of the `info` library as shown here: https://github.com/munki/munki/compare/v5.6.1...v5.6.2, as this was the only change in the release.

```bash
graffino@Graffinos-MBP Alfred % autopkg run Alfred.munki.recipe -vvv 
WARNING: Did not load any default preferences.
Processing Alfred.munki.recipe...
WARNING: Alfred.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3.1',
 'DOWNLOAD_URL': 'https://XXXXXXXXXXXXX.XXX/autopkg/alfred.pkg',
 'MUNKI_CATEGORY': 'Ulitilites',
 'MUNKI_REPO': '""',
 'MUNKI_REPO_PLUGIN': 'SimpleMDMRepo',
 'MUNKI_REPO_SUBDIR': 'apps',
 'NAME': 'Alfred',
 'PARENT_RECIPES': ['/Users/graffino/Downloads/Alfred/Alfred.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred',
 'RECIPE_DIR': '/Users/graffino/Downloads/Alfred',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/graffino/Downloads/Alfred/Alfred.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        ''],
 'extract_icon': True,
 'pkginfo': {'blocking_applications': ['Alfred.app'],
             'catalogs': ['Manual • Munki • Everyone'],
             'category': 'Ulitilites',
             'description': 'Alfred is an award-winning app for macOS which '
                            'boosts your efficiency with hotkeys, keywords, '
                            'text expansion and more. Search your Mac and the '
                            'web, and be more productive with custom actions '
                            'to control your Mac.',
             'developer': 'Running with Crayons',
             'display_name': 'Alfred*',
             'name': 'Alfred',
             'unattended_install': True},
 'verbose': 3}
URLDownloader
{'Input': {'filename': 'Alfred.pkg',
           'url': 'https://packages.graffino.net/autopkg/alfred.pkg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg
{'Output': {'pathname': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
MunkiImporter
{'Input': {'MUNKI_REPO': '""',
           'MUNKI_REPO_PLUGIN': 'SimpleMDMRepo',
           'extract_icon': True,
           'pkg_path': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg',
           'pkginfo': {'blocking_applications': ['Alfred.app'],
                       'catalogs': ['Manual • Munki • Everyone'],
                       'category': 'Ulitilites',
                       'description': 'Alfred is an award-winning app for '
                                      'macOS which boosts your efficiency with '
                                      'hotkeys, keywords, text expansion and '
                                      'more. Search your Mac and the web, and '
                                      'be more productive with custom actions '
                                      'to control your Mac.',
                       'developer': 'Running with Crayons',
                       'display_name': 'Alfred*',
                       'name': 'Alfred',
                       'unattended_install': True},
           'repo_subdirectory': 'apps'}}
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 16, in __init__
    from munkilib.admin import munkiimportlib
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 34, in <module>
    from .. import osinstaller
  File "/usr/local/munki/munkilib/osinstaller.py", line 47, in <module>
    from . import info
  File "/usr/local/munki/munkilib/info.py", line 37, in <module>
    import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 18, in <module>
    "/System/Library/Frameworks/CoreServices.framework/CoreServices"
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 136, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 130, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 98, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 292, in main
    self.env["force_munki_repo_lib"],
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 168, in _fetch_repo_library
    munki_repo, munki_repo_plugin, munkilib_dir, repo_subdirectory
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 20, in __init__
    f"munkilib import error: {str(err)}\nMunki tools version 3.2.0.3462 or "
autopkglib.ProcessorError: munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
Failed.
Receipt written to /Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/receipts/Alfred.munki-receipt-20220207-074021.plist

The following recipes failed:
    Alfred.munki.recipe
        Error in com.graffino.autopkg.munki.alfred: Processor: MunkiImporter: Error: munkilib import error: Framework CoreServices could not be found
        Munki tools version 3.2.0.3462 or later is required.

Nothing downloaded, packaged or imported.
```

**Comment by gregneagle** [comment]
This is an _AutoPkg_ issue.
