### ISSUE TITLE
PyObjC - possibly needs updating to 9.1.1?

### ISSUE THREAD

**Issue by carlashley** [munki/munki#1178]
When building munki from `main` (last log commit `b6155af3dd397e6488200846a79ec4e80b95a1da`), some of the `pyobjc` wheels fail.
This is using the standard `py3_requirements.txt` file _and_ I can reproduce the same issue with a standalone `relocatable-python` instance.

macOS 13.4 (22F66), Xcode 14.3 (14E222b), Apple M1, building Python 3.10.10 (munki, also fails building 3.11.2) 3.11.2 (relocatable-python).

Updated the `py3_requirements.txt` to point to 9.1.1 version targets for the pyobjc packages and the build succeeds.

```
Building wheels for collected packages: pyobjc-core, pyobjc-framework-Cocoa
  Building wheel for pyobjc-core (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [211 lines of output]
```
[bunch of output]

```
 clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Volumes/WORK01/work/git/github/munki/Python.framework/Versions/3.10/include/python3.10 -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c Modules/objc/class-builder.m -o build/temp.macosx-10.9-universal2-cpython-310/Modules/objc/class-builder.o -g -fexceptions -fno-objc-arc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wformat=2 -W -Wpointer-arith -Wmissing-declarations -Wnested-externs -W -Wno-import -Wno-unknown-pragmas -Wshorten-64-to-32 -Werror -I/usr/include/ffi -fvisibility=hidden -g -O3 -flto=thin -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DPyObjC_BUILD_RELEASE=1303
      Modules/objc/class-builder.m:1999:17: error: code will never be executed [-Werror,-Wunreachable-code]
                      PyMem_Free(argbuf);
                      ^~~~~~~~~~
      Modules/objc/class-builder.m:1990:17: error: code will never be executed [-Werror,-Wunreachable-code]
                      PyMem_Free(argbuf);
                      ^~~~~~~~~~
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyobjc-core
  Running setup.py clean for pyobjc-core
  Building wheel for pyobjc-framework-Cocoa (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [519 lines of output]
```
[bunch of output]
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Volumes/WORK01/work/git/github/munki/Python.framework/Versions/3.10/include/python3.10 -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c Modules/_Foundation.m -o build/temp.macosx-10.9-universal2-cpython-310/Modules/_Foundation.o -Wno-deprecated-declarations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -DPyObjC_BUILD_RELEASE=1303 -Werror
      In file included from Modules/_Foundation.m:14:
      Modules/_Foundation_string.m:36:9: error: variable 'buf2' is uninitialized when used here [-Werror,-Wuninitialized]
          if (buf2 != Py_None && buf2 != PyObjC_NULL) {
              ^~~~
      Modules/_Foundation_string.m:18:34: note: initialize the variable 'buf2' to silence this warning
          PyObject *        buf1, *buf2;
                                       ^
                                        = NULL
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyobjc-framework-Cocoa
  Running setup.py clean for pyobjc-framework-Cocoa
Failed to build pyobjc-core pyobjc-framework-Cocoa
ERROR: Could not build wheels for pyobjc-core, pyobjc-framework-Cocoa, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/tmp/relocatable-python-git/make_relocatable_python_framework.py", line 108, in <module>
    main()
  File "/tmp/relocatable-python-git/make_relocatable_python_framework.py", line 94, in main
    install_extras(
  File "/private/tmp/relocatable-python-git/locallibs/install.py", line 114, in install_extras
    install_requirements(requirements_file, framework_path, version)
  File "/private/tmp/relocatable-python-git/locallibs/install.py", line 79, in install_requirements
    subprocess.check_call(cmd, env=pip_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./Python.framework/Versions/3.10/bin/python3.10', '-s', '-m', 'pip', 'install', '-r', './code/tools/py3_requirements.txt']' returned non-zero exit status 1.
```

**Comment by carlashley** [comment]
This _might_ be related to https://github.com/ronaldoussoren/pyobjc/issues/550

**Comment by gregneagle** [comment]
It works here for me without error. Not that I'm dismissing your report, but I'd want to understand why it works for me but fails for you before making any changes on my end.

**Comment by gregneagle** [comment]
The Munki6dev branch now builds a Python 3.10.11 framework with PyObjC 9.1.1. I haven't actually _tested_ the result, but it builds OK (here).
