### ISSUE TITLE
munkiimport and makepkginfo crash with distribution-style packages containing a payload-free package

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1179]
Demo:
```shell
$ pkgbuild --nopayload --identifier com.foo.bar --version 1.0 bar.pkg
pkgbuild: Wrote package to bar.pkg
$ productbuild --package bar.pkg bar_dist.pkg
productbuild: Wrote product to bar_dist.pkg
$ makepkginfo bar_dist.pkg
Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 143, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 117, in main
    pkginfo = pkginfolib.makepkginfo(installeritem, options)
  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 469, in makepkginfo
    pkginfo = get_catalog_info_from_path(installeritem, options)
  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 103, in get_catalog_info_from_path
    cataloginfo = pkgutils.getPackageMetaData(pkgpath)
  File "/usr/local/munki/munkilib/pkgutils.py", line 881, in getPackageMetaData
    if (MunkiLooseVersion(infoitem['version']) >
TypeError: string indices must be integers
```

**Comment by gregneagle** [comment]
Fixed in https://github.com/munki/munki/commit/d1db45e6bcc0aee4afefcab5eea393d2b09d7d7c
Will ship with next release.
