### ISSUE TITLE
munkiimport  and munkilib/pkgutils.py crash with packages containing .dist file 

### ISSUE THREAD

**Issue by ManishaDeshmukh** [munki/munki#1192]
**Error:**

Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 608, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 379, in main
    pkginfo = pkginfolib.makepkginfo(installer_item, options)
  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 450, in makepkginfo
    pkginfo = get_catalog_info_from_dmg(installeritem, options)
  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 194, in get_catalog_info_from_dmg
    cataloginfo = get_catalog_info_from_path(itempath, options)
  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 103, in get_catalog_info_from_path
    cataloginfo = pkgutils.getPackageMetaData(pkgpath)
  File "/usr/local/munki/munkilib/pkgutils.py", line 854, in getPackageMetaData
    for infoitem in receiptinfo['receipts']:
TypeError: list indices must be integers or slices, not str

**Issue Analysis:** 
Issue is happening with packages which contains .dist file. After checking code from pkgutils.py, below is the analysis

- Receipts information (from pkgutils.py) from all func are returned as a dictionary with key 'receipts'
- Packages which contains .dist goes in parsePkgRefs func.
- But parsePkgRefs simply returning info and not embedding in a dictionary with key 'receipts'
- Which simple keeps info as an array.
- Therefore File "/usr/local/munki/munkilib/pkgutils.py", line 854, in getPackageMetaData
                     for infoitem in receiptinfo['receipts']: it does not find anything which leads to a crash.

**Note**
Just for checking I changed return type for func parsePkgRefs from 
`return info`
to
`return {"receipts": info}`
It started working.

**Comment by gregneagle** [comment]
Could you point to package that triggers this issue?

**Comment by gregneagle** [comment]
Your fix would break the getFlatPackageInfo() function in pkgutils.py, because it calls parsePkgRefs() with code like
```
receiptarray = parsePkgRefs(packageinfoabspath)
```
and then later returns that info like so:
```
    info = {
        "receipts": receiptarray,
        "product_version": productversion
    }
    return info
```

But your analysis is in the right direction. It would still be greatly useful to have a package that triggers this issue. I'm guessing it would be a bundle-style package with a .dist file?

**Comment by ManishaDeshmukh** [comment]
Hi @gregneagle ,

Thanks for your quick reply. Yes for actual fix, need to check at other places too. I just tried to check the issue. 
I have sent pkg to you over email. Please let me know if it is not accessible.

**Comment by gregneagle** [comment]
OK, I also found an old Office 2011 installer pkg that triggers the issue. I have a fix, but need to verify it doesn't cause unexpected issues with other pkg formats.

**Comment by gregneagle** [comment]
This is the fix I'm currently testing:
```
$ git diff code/client/munkilib/pkgutils.py
diff --git a/code/client/munkilib/pkgutils.py b/code/client/munkilib/pkgutils.py
index 7c5fd3f4..9931fde0 100644
--- a/code/client/munkilib/pkgutils.py
+++ b/code/client/munkilib/pkgutils.py
@@ -587,12 +587,6 @@ def getOnePackageInfo(pkgpath):
             pkginfo['packageid'] = 'BAD PLIST in %s' % \
                                     os.path.basename(pkgpath)
             pkginfo['version'] = '0.0'
-        ## now look for applications to suggest for blocking_applications
-        #bomlist = getBomList(pkgpath)
-        #if bomlist:
-        #    pkginfo['apps'] = [os.path.basename(item) for item in bomlist
-        #                        if item.endswith('.app')]
-
     else:
         # look for old-style .info files!
         infopath = os.path.join(
@@ -626,7 +620,8 @@ def getBundlePackageInfo(pkgpath):
             if item.endswith('.dist'):
                 filename = os.path.join(bundlecontents, item)
                 # return info using the distribution file
-                return parsePkgRefs(filename, path_to_pkg=bundlecontents)
+                receiptarray = parsePkgRefs(filename, path_to_pkg=bundlecontents)
+                return {"receipts": receiptarray}
 
         # no .dist file found, look for packages in subdirs
         dirsToSearch = []
@@ -670,7 +665,8 @@ def getReceiptInfo(pkgname):
             info = getBundlePackageInfo(pkgname)
 
     elif pkgname.endswith('.dist'):
-        info = parsePkgRefs(pkgname)
+        receiptarray = parsePkgRefs(pkgname)
+        info = {"receipts": receiptarray}
 
     return info
```

**Comment by ManishaDeshmukh** [comment]
Above changes fixed the crash. 
I did verify on couple of different packages.

**Comment by gregneagle** [comment]
The things we’ll need to test are not only does this  fix bundle-style metapackages, but also that they don’t break with bundle-style simple packages, flat component packages, and flat distribution packages. I believe I’ve tested all of those successfully.

**Comment by tjsoftworks** [comment]
unsubscribe

**Comment by gregneagle** [comment]
@tjsoftworks I don't know how you subscribed to notifications to this issue, but replying with 'unsubscribe' appears to be doing nothing. You _are_ in the 'participants' list for whatever reason. I think you'll have to login to GitHub, navigate to the issue, and unsubscribe here: 
<img width="343" alt="image" src="https://github.com/munki/munki/assets/700560/16cd06de-e5d5-4567-9970-1aab69535acd">

**Comment by gregneagle** [comment]
This is pushed to the Munk6dev branch here: https://github.com/munki/munki/commit/8134cedbc2aca8ff4a842fb8cfd656233ee3c650 and will be in the next release of Munki.

**Comment by gregneagle** [comment]
Beta here: https://github.com/munki/munki/releases/tag/v6.3.5b2
