### ISSUE TITLE
validating receipts dicts

### ISSUE THREAD

**Issue by timsutton** [munki/munki#462]
Just ran into an issue where I get a traceback caused by an invalid receipt item in a newly-imported pkginfo - not the fault of makepkginfo, just bad pkginfo manipulation.

```python
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1012, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 725, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2944, in check
    installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2095, in processManifestForKey
    installinfo, cataloglist)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2135, in processManifestForKey
    item, cataloglist, installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2209, in processRemoval
    if evidenceThisIsInstalled(item):
  File "/usr/local/munki/munkilib/updatecheck.py", line 1408, in evidenceThisIsInstalled
    analyzeInstalledPkgs()
  File "/usr/local/munki/munkilib/updatecheck.py", line 238, in analyzeInstalledPkgs
    addPackageids(catalogitems, itemname_to_pkgid, pkgid_to_itemname)
  File "/usr/local/munki/munkilib/updatecheck.py", line 141, in addPackageids
    vers = receipt['version']
```

An immediate fix might be to just add the same "and if 'version' in receipt" clause here:
https://github.com/munki/munki/blob/256ae6938357eb6daf240204ff00c96dcd653ad2/code/client/munkilib/updatecheck.py#L139

..which is already in use here:
https://github.com/munki/munki/blob/256ae6938357eb6daf240204ff00c96dcd653ad2/code/client/munkilib/updatecheck.py#L84

But then I saw there's other existing validation code:
https://github.com/munki/munki/blob/256ae6938357eb6daf240204ff00c96dcd653ad2/code/client/munkilib/updatecheck.py#L690-L694

Wondering if a better way to address this might be to just refactor this into a validation function that these other code points can call, and it returns `(True, [])` if the receipts dict contains all expected keys, and `(False, [list of missing keys])` otherwise, so that the callers can handle it and log the error.

Does this seem reasonable? If so I can attempt a PR for this.

**Comment by gregneagle** [comment]
Maybe your first instinct is best; abstraction and code reuse is usually a good thing, but in this case, this seems clearer:

```python
                if 'packageid' in receipt and 'version' in receipt:
                    pkgid = receipt['packageid']
                    vers = receipt['version']
```

Compared to:

```python
                receipt_ok, missing_fields = verify_receipt_fields(receipt)
                if receipt_ok:
                    pkgid = receipt['packageid']
                    vers = receipt['version']
                    <...>
                else:
                    munkicommon.display_warning("Yikes")
                    # cobble together a helpful message using missing_fields, etc
```

and then finding all the places to retrofit the new verify_receipt_fields function. I just think maybe the cost/benefit ratio isn't high enough to refactor that right now, but I'm not _opposed_ to it, either.

**Comment by timsutton** [comment]
I started down the simpler path, but I see that by that point in the code, `analyzeInstalledPkgs()` is already going assuming it has that pkgname to work with and that it would be able to do something useful with the pkg ids and versions. We could validate it at some earlier point, but maybe better to just catch this in `makecatalogs` and warn about the missing keys, not adding the item to the catalogs? (In the same way that it currently rejects a pkginfo missing a `name`.)

This comes back to a bigger pkginfo linter/validator component that could be useful in a few ways, but that's obviously a bigger project.

**Comment by timsutton** [comment]
Just to show some actual code for the idea of validating at `makecatalogs` rather than within the client run:

https://github.com/timsutton/munki/commit/190eac7551205898cee794219285a0a9efbd0c24
