### ISSUE TITLE
cannnot import Android Studio 1.2 beta

### ISSUE THREAD

**Issue by hymmm** [munki/munki#469]
I don't know whether it's a issue with munki or Android Studio, but anyway I cannot import it.

$ munkiimport Android\ Studio.app/
Making disk image containing Android Studio.app...
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1106, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 880, in main
    dmg_path = makeDMG(installer_item)
  File "/usr/local/munki/munkiimport", line 86, in makeDMG
    print output.rstrip('\n').encode('UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 25: ordinal not in range(128)

using 2.2.4.

**Comment by gregneagle** [comment]
It would have saved me a fair amount of time had you specified a download URL for the exact item that caused you this issue, I tried searching for "Android Studio" and imported the first thing I found without issue:

```
% munkiimport ~/Downloads/android-studio-ide-135.1740770-mac.dmg
      Item name [Android Studio]: 
   Display name: Android Studio
    Description: Some horrible Java-based developer thing
        Version [1.1.0]: 
       Category: Developer
      Developer: Google
       Catalogs [testing]: 

      Item name: Android Studio
   Display name: Android Studio
    Description: Some horrible Java-based developer thing
        Version: 1.1.0
       Category: Developer
      Developer: Google
       Catalogs: testing

Import this item? [y/n] y
Upload item to subdirectory path []: developer
No existing product icon found.
Attempt to create a product icon? [y/n] y
Attempting to extract and upload icon...
Created icon: /Users/Shared/munki_repo/icons/Android Studio.png
Copying android-studio-ide-135.1740770-mac.dmg to /Users/Shared/munki_repo/pkgs/developer/android-studio-ide-135.1740770-mac-1.1.0.dmg...
Saving pkginfo to /Users/Shared/munki_repo/pkgsinfo/developer/Android Studio-1.1.0.plist...
Rebuild catalogs? [y/n] y
Rebuilding catalogs at /Users/Shared/munki_repo...
```

Then I noticed the "1.2 beta" bit in the title, and then found this page: http://tools.android.com/download/studio/canary/1-2-beta, where I downloaded the mac.zip and imported it:

```
% munkiimport ~/Downloads/Android\ Studio.app
Making disk image containing Android Studio.app...
hdiutil: create failed - error -5341
Disk image creation failed.
Could not convert /Users/gneagle/Downloads/Android Studio.app to a disk image.
```

This is that stupid hdiutil bug we've seen, so now I manually create a disk image, specifying a "large enough"size:
```
~/Downloads % hdiutil create -size 500m -srcfolder Android\ Studio.app AndroidStudio.dmg
..................................................................................................
created: /Users/gneagle/Downloads/AndroidStudio.dmg
```

Now let's import _that_:

```
~/Downloads % munkiimport AndroidStudio.dmg 
This item is similar to an existing item in the repo:
            Item name: Android Studio
         Display name: Android Studio
          Description: Some horrible Java-based developer thing
              Version: 1.1.0
  Installer item path: developer/android-studio-ide-135.1740770-mac-1.1.0.dmg

Use existing item as a template? [y/n] y
Copying category: Developer
Copying developer: Google
      Item name [Android Studio]: 
   Display name [Android Studio]: 
    Description [Some horrible Java-based developer thing]: 
        Version [1.2]: 
       Category [Developer]: 
      Developer [Google]: 
       Catalogs [testing]: 

      Item name: Android Studio
   Display name: Android Studio
    Description: Some horrible Java-based developer thing
        Version: 1.2
       Category: Developer
      Developer: Google
       Catalogs: testing

Import this item? [y/n] y
Copying AndroidStudio.dmg to /Users/Shared/munki_repo/pkgs/developer/AndroidStudio-1.2.dmg...
Saving pkginfo to /Users/Shared/munki_repo/pkgsinfo/developer/Android Studio-1.2.plist...
Rebuild catalogs? [y/n] y
Rebuilding catalogs at /Users/Shared/munki_repo...
```

That worked, too. So I guess I need more info in order to replicate this...

**Comment by hymmm** [comment]
Oh, sorry, I should give an URL for you... yes,  http://tools.android.com/download/studio/canary/1-2-beta　is the one.

And thanks, it worked as the way you've suggested. (error message is different but anyway...)
