### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by majorsl** [munki/munki#486]
I was attempting to make an install for Übersicht.app.  I believe the Ü is the issue.  

Manually creating a dmg called Ubersicht and dropping the .app into it was my workaround.

Details below:

Making disk image containing Übersicht.app...
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1106, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 880, in main
    dmg_path = makeDMG(installer_item)
  File "/usr/local/munki/munkiimport", line 86, in makeDMG
    print output.rstrip('\n').encode('UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 28: ordinal not in range(128)

**Comment by majorsl** [comment]
Looks like when there is and icon file that has a similar character in it, it causes errors with the client as well:

Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1013, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 725, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 3104, in check
    download_icons(item_list)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2776, in download_icons
    icon_url = icon_base_url + urllib2.quote(icon_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1285, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u0308'

**Comment by gregneagle** [comment]
For the second half of your issue, this appears to be a problem with Python's urllib2.quote() function:

urllib2.quote(u"Übersicht")

Will raise the same Exception. For now, I'd recommend not using non-ASCII characters in filenames; as these get encoded into URLs.

The first part of the issue (with munkiimport) has to do with correctly passing Unicode strings between two command-line tools (munkiimport and makepkginfo) inside of Python. I have yet to figure out all the required incantations.

**Comment by majorsl** [comment]
Thanks, not a deal breaker, I've worked around it all as you suggested even before opening the issue here. Just wanted to get it on someone's radar for the future.

**Comment by gregneagle** [comment]
Attempt to deal with the second part of your issue here: https://github.com/munki/munki/commit/b37a5146240abefd7a138ae6dd6c215f4ff5b544

**Comment by ms-studio** [comment]
Interestingly, I get a similar error message when trying to munkiimport Apple's Numbers.app:

    Making disk image containing Numbers.app...
    Traceback (most recent call last):
      File "/usr/local/munki/munkiimport", line 1113, in <module>
        main()
      File "/usr/local/munki/munkiimport", line 886, in main
        dmg_path = makeDMG(installer_item)
      File "/usr/local/munki/munkiimport", line 86, in makeDMG
        print output.rstrip('\n').encode('UTF-8')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)

**Comment by ms-studio** [comment]
PS: The issue goes away when I switch the OSX system language from French to English.
