### ISSUE TITLE
Munkiimport Having issues Configuring.

### ISSUE THREAD

**Issue by BaddMann** [munki/munki#589]
Using this version 
https://munkibuilds.org/2.6.1.2702/

MunkiImport wasn't able to configure

```
munkiimport --configure
Unhandled exception in thread started by <function insert_default_text at 0x1120c60c8>
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 55, in insert_default_text
    readline.insert_text(text.encode(sys.stdout.encoding))
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1136, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 807, in main
    configure()
  File "/usr/local/munki/munkiimport", line 725, in configure
    _prefs[key] = raw_input_with_default('%15s: ' % prompt, pref(key))
  File "/usr/local/munki/munkiimport", line 62, in raw_input_with_default
    return raw_input().decode(sys.stdin.encoding)
```

Don't Have more detail than that.

**Comment by gregneagle** [comment]
Can't replicate:

```
gneagle@humantorch:~ % munkiimport --version
2.6.1.2702
gneagle@humantorch:~ % munkiimport --configure
Path to munki repo (example: /Volumes/repo): /Volumes/repo
```

Could you share the result of `defaults read com.googlecode.munki.munkiimport` ?

**Comment by gregneagle** [comment]
Possible this commit will address the issue: https://github.com/munki/munki/commit/1288f7a7f2ee895955b39a3526360c8233a4b256

but I'd still like to see the output of `defaults read com.googlecode.munki.munkiimport` (sanitized, if you like) to confirm my theory.

**Comment by gregneagle** [comment]
Fixed here https://github.com/munki/munki/commit/1f82f66ac748b89e6027f5565bf9133c53cd95c8

**Comment by BaddMann** [comment]
I'm Sorry, I've got to modify a gmail filter, don't use Github enough.
