### ISSUE TITLE
Munki crashes if 'managed_uninstalls' has any items

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#610]
Munki version: 2.7.0.2756

While running from CLI this comes:

ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1049, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 743, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck.py", line 3035, in check
    installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2134, in processManifestForKey
    installinfo, cataloglist)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2158, in processManifestForKey
    installinfo, cataloglist)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2134, in processManifestForKey
    installinfo, cataloglist)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2174, in processManifestForKey
    item, cataloglist, installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2249, in processRemoval
    if evidenceThisIsInstalled(item):
  File "/usr/local/munki/munkilib/updatecheck.py", line 1426, in evidenceThisIsInstalled
    if item_pl['name'] in pkgdata['installed_names']:
TypeError: 'NoneType' object has no attribute '__getitem__'

Happens if there are any removable items in 'managed_uninstalls'.
Problem disappeared when managed_uninstalls was empied.
All pkginfos for removable items are fine.

**Comment by gregneagle** [comment]
Please test to see if this fixes it: https://github.com/munki/munki/commit/a322efd1201406777b976cc7674796235e3a15a1

**Comment by MiqViq** [comment]
Yes,

After 2 tests seems like you nailed it.

Thx, again on behalf of me & others.

-MiqViq
