### ISSUE TITLE
managedsoftware --installonly failing mounting DMG with UnicodeDecodeError

### ISSUE THREAD

**Issue by fuzzycheck** [munki/munki#652]
Hi,
  I'm not sure how to solve this. 
  I'm testing Munkitools 2.8.0 on Macos Sierra beta.
  My locale is this:

bash-3.2# locale
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL

   When I run the command "managedsoftware --installonly", I get this error on some DMG files. Not sure, but it seems only on DMG containing a .app, and not on DMG containing a .pkg.
The error:

ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1047, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 842, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 232, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 1277, in run
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 719, in installWithInfo
    retcode = copyFromDMG(itempath, item.get('items_to_copy'))
  File "/usr/local/munki/munkilib/installer.py", line 535, in copyFromDMG
    mountpoints = munkicommon.mountdmg(dmgpath)
  File "/usr/local/munki/munkilib/munkicommon.py", line 1001, in mountdmg
    'Error: "%s" while mounting %s.' % (err.rstrip(), dmgname))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)

  It looks like the error is coming from mixing a Unicode string u'/Library/...'  with an other encoding (UTF-8?):

cmd= ['/usr/bin/hdiutil', 'attach', u'/Library/Managed Installs/Cache/Eracent-1.0.dmg', '-mountRandom', '/tmp', '-nobrowse', '-plist']

   I solved the error by encoding the string in mountdmg():

def mountdmg(dmgpath, use_shadow=False, use_existing_mounts=False):
    """
    Attempts to mount the dmg at dmgpath
    and returns a list of mountpoints
    If use_shadow is true, mount image with shadow file
    """
    dmgpath = dmgpath.encode('UTF-8')

   So maybe this solution is valid only for my locale? It looks like the packages install fine when no user is logged in. I'm thinking doing something like 

      dmgpath = dmgpath.encode(sys.getdefaultencoding())

   But maybe this is not the right place to change this dmgpath. Any idea on this?
  

Cheers,
fuzzycheck

**Comment by fuzzycheck** [comment]
More info on the problem. 
In fact I don't think it is related to my locale.

In munkicommon.py, the "pref" function tries to set non-unicode defaults:

def pref(pref_name):
...
default_prefs = {
        'ManagedInstallDir': '/Library/Managed Installs',
....
}
    pref_value = CFPreferencesCopyAppValue(pref_name, BUNDLE_ID)

  The problem comes from the call to CFPreferencesCopyAppValue. That is the function returning a unicode value:

>>> CFPreferencesCopyAppValue('ManagedInstallDir', BUNDLE_ID)
u'/Library/Managed Installs'

   And it seems to be the normal return encoding, according to this page:
https://searchcode.com/codesearch/view/2208782/

v = CFPreferencesCopyAppValue("Default Window Settings", "com.apple.Terminal")
        self.assertIsInstance(v, unicode)

    So there 2 are 2 solutions in my opinion:
- modify the pref function to encode all return values of CFPreferencesCopyAppValue to UTF-8
- modify only the mountdmg function to encode dmpath to UTF-8.

  The first solution might break other things. So would it be OK if I submit a pull request to add "dmgpath = dmgpath.encode('UTF-8')" ?

Cheers,
Fuzzycheck

**Comment by gregneagle** [comment]
I'd like to better understand the issue first. Can you provide (or point me towards) a dmg that triggers the issue?

**Comment by fuzzycheck** [comment]
Hi,
  for example, ADPassMon 2.20.18. 
https://github.com/macmule/ADPassMon/releases/tag/2.20.18

   From the Terminal, it fails:

Starting...
    Performing preflight tasks...
Installing ADPassMon (1 of 1)...
    Mounting disk image ADPassMon-2.20.18.dmg...
ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1052, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 844, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 232, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 1222, in run
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 680, in installWithInfo
    retcode = copyFromDMG(itempath, item.get('items_to_copy'))
  File "/usr/local/munki/munkilib/installer.py", line 496, in copyFromDMG
    mountpoints = munkicommon.mountdmg(dmgpath)
  File "/usr/local/munki/munkilib/munkicommon.py", line 1009, in mountdmg
    'Error: "%s" while mounting %s.' % (err.rstrip(), dmgname))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
bash-3.2# file /Library/Managed\ Installs/Cache/ADPassMon-2.20.18.dmg 
/Library/Managed Installs/Cache/ADPassMon-2.20.18.dmg: zlib compressed data

   This DMG contains the application, not a pkg:

bash-3.2# ls -lh !$
ls -lh /Library/Managed\ Installs/Cache/ADPassMon-2.20.18.dmg
-rw-r--r--@ 1 root  admin   908K 22 aoû 19:13 /Library/Managed Installs/Cache/ADPassMon-2.20.18.dmg
bash-3.2# hdiutil attach !$
hdiutil attach /Library/Managed\ Installs/Cache/ADPassMon-2.20.18.dmg
prévue   CRC32 $14A6F98F
/dev/disk1          	GUID_partition_scheme          	
/dev/disk1s1        	Apple_HFS                      	/Volumes/Applications
bash-3.2# ls -l /Volumes/Applications
total 0
d-wx-wx-wt@ 2 501  staff   68 27 fév 17:07 .Trashes
drwxr-xr-x  3 501  staff  102 27 fév 16:34 ADPassMon.app
bash-3.2# 

   Logging out the current user, and running the commands through ARD, it succeeds:

Starting...
    Performing preflight tasks...
Installing ADPassMon (1 of 1)...
    Mounting disk image ADPassMon-2.20.18.dmg...
    Copying ADPassMon.app to /Applications/ADPassMon.app...
    The software was successfully installed.
Finishing...
    Performing postflight tasks...

  Now testing again through ARD, with current user logged in, it fails:

Starting...
    Performing preflight tasks...
Installing ADPassMon (1 of 1)...
    Mounting disk image ADPassMon-2.20.18.dmg...
ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1052, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 844, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 232, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 1222, in run
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 680, in installWithInfo
    retcode = copyFromDMG(itempath, item.get('items_to_copy'))
  File "/usr/local/munki/munkilib/installer.py", line 496, in copyFromDMG
    mountpoints = munkicommon.mountdmg(dmgpath)
  File "/usr/local/munki/munkilib/munkicommon.py", line 1009, in mountdmg
    'Error: "%s" while mounting %s.' % (err.rstrip(), dmgname))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)


    
Cheers
