### ISSUE TITLE
makecatalogs traceback on Windows

### ISSUE THREAD

**Issue by gmarnin** [munki/munki#666]
python D:\path\mwa2_env\munki\code\client\makecatalogs D:\path\munki\
WARNING: FoundationPlist is not available, using plistlib instead.
Traceback (most recent call last):
  File "D:\path\mwa2_env\munki\code\client\makecatalogs", line 417, in <module>
    main()
  File "D:\path\mwa2_env\munki\code\client\makecatalogs", line 414, in main
    makecatalogs(repopath, options)
  File "D:\path\mwa2_env\munki\code\client\makecatalogs", line 135, in makecatalogs
    iconpath = filepath.rsplit(iconspath + '/', 1)[1]
IndexError: list index out of range

**Comment by gregneagle** [comment]
Could you please make a Pull Request with this fix?

**Comment by keeleysam** [comment]
@gregneagle the fix is in #667

**Comment by gregneagle** [comment]
Merged, so closing
