### ISSUE TITLE
Munki 2.9.0.3029 traceback on uninstall

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#706]
Client running 2.9.0.3029 fails with the following error when trying to uninstall a pkg.

```
Removing crankd (1 of 2)...
    Gathering information on installed packages...
	0ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1033, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 837, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 234, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer/core.py", line 723, in run
    removallist, only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer/core.py", line 526, in process_removals
    forcedeletebundles=True)
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 802, in removepackages
    if not init_database(forcerebuild=rebuildpkgdb):
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 437, in init_database
    import_package(receiptpath, curs)
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 242, in import_package
    plist.get('Bundle versions string, short'), '1.0')
TypeError: get_objectForKey_() takes at most 3 arguments (4 given)
```

Running `managedsoftwareupdate --installonly -vvvv` immediately again resulted in:

```
Removing crankd (1 of 2)...
    select pkg_key from pkgs where pkgid = com.github.munki.pkg.crankd
    select pkg_key from pkgs where pkgname = com.github.munki.pkg.crankd
ERROR: com.github.munki.pkg.crankd not found in database.
    pkgkeys: []
ERROR: Uninstall of crankd failed.
    Checking for skipped items that require crankd_application_usage
    crankd has these prerequisites:
Removing crankd_application_usage (2 of 2)...
    select pkg_key from pkgs where pkgid = com.github.munki.pkg.crankd_application_usage
    select pkg_key from pkgs where pkgname = com.github.munki.pkg.crankd_application_usage
ERROR: com.github.munki.pkg.crankd_application_usage not found in database.
    pkgkeys: []
ERROR: Uninstall of crankd_application_usage failed.
Finishing...
```

Manually running `pkgutil --pkgs | grep crankd` shows the receipts are in the recipe database:

```
$ pkgutil --pkgs | grep crankd
com.github.munki.pkg.crankd
com.github.munki.pkg.crankd_application_usage
```

Confirmed the payload of the installers are still on disk.

-Eric

**Comment by poundbangbash** [comment]
A 2nd machine with the same version of munki client 2.9.0.3029 processed the same manifest changes however this one was successful in its uninstallation of the two packages.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/edb8f43d2b1b5142d488c3bdf90f0a0c66ab6901 should address the traceback.
