### ISSUE TITLE
UnicodeDecodeError during munkiimport

### ISSUE THREAD

**Issue by fuzzycheck** [munki/munki#715]
Hi

  Problem: I receive a UnicodeDecodeError on an output message which needs to be decoded, not encoded.

My environment:
Macos 10.12.3
munkiimport: 2.8.2.2855

  munkiimport was working fine until a few days ago. I mounted a Flash dmg file, and unmounting it seems to have caused a problem. Since then any munkiimport I try gives me this error:

$ munkiimport /Applications/Firefox.app/
Making disk image containing Firefox.app...
TYPE <type 'str'>
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1267, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 1028, in main
    dmg_path = make_dmg(installer_item)
  File "/usr/local/munki/munkiimport", line 228, in make_dmg
    print output.rstrip('\n').encode('UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 172: ordinal not in range(128)

   The issue is in fact that "output" is a "str". It needs to be decoded, not encoded. I changed line 228
to this:

        print "TYPE", type(output)
        print output.rstrip('\n').decode('UTF-8')

   Now it works better, with the error message correctly printed:

$ munkiimport /Applications/Firefox.app/
Making disk image containing Firefox.app...
TYPE <type 'str'>
2017-03-05 10:44:12.385 hdiutil[35652:6815648] kCFURLVolumeIsAutomountedKey missing for file:///Volumes/Flash%20Player/: Error Domain=NSCocoaErrorDomain Code=260 "The file “Flash Player” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Volumes/Flash%20Player/, NSFilePath=/Volumes/Flash Player, NSUnderlyingError=0x7ff275f01030 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

BR

**Comment by gregneagle** [comment]
I found a couple other ones like that. This commit: https://github.com/munki/munki/commit/470ee979bf1d46fa993d38e1d5aa27948f14f790 replaces those .encode() attempts to .decode().
