### ISSUE TITLE
Munki3  - munkiimport won't run if all catalog doesn't exist

### ISSUE THREAD

**Issue by fuzzylogiq** [munki/munki#730]
Testing 3.0.0.3175 I get the following if I try to run munkiimport (after configuring it) before the `all` catalog exists:

$ makecatalogs

WARNING: Did not create catalog all because it is empty

$ munkiimport ~/Downloads/Firefox\ 52.0.dmg
Traceback (most recent call last):
 File "/usr/local/munki/munkiimport", line 1077, in <module>
   main()
 File "/usr/local/munki/munkiimport", line 867, in main
   matchingpkginfo = find_matching_pkginfo(repo, pkginfo)
 File "/usr/local/munki/munkiimport", line 508, in find_matching_pkginfo
   catdb = make_catalog_db(repo)
 File "/usr/local/munki/munkiimport", line 404, in make_catalog_db
   plist = repo.get('catalogs/all')
 File "/usr/local/munki/munkilib/munkirepo/FileRepo.py", line 207, in get
   fileref = open(repo_filepath)
IOError: [Errno 2] No such file or directory: u'/Users/Shared/munki_repo/catalogs/all'

FileRepo.py appears to only raise a RepoError on OSErrors and not IOErrors, which causes this. But should munkiimport really be failing if it can't open the `all` catalog? (which it does on line 406)

If I `touch /Users/Shared/munki_repo/catalogs/all` it works.

**Comment by gregneagle** [comment]
You might find it's been addressed in a more recent commit. :-)
