### ISSUE TITLE
[v3] munkiimport traceback when remote repo not accessible

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#731]
Attempting to use munkiimport (v.3.0.0.3173) when the remote repo was not accessible due to being away from the testing network it is configured on, I get the following traceback:

```
air:~ eholtam$ munkiimport /Users/eholtam/Downloads/smartmontools-6.5-1.dmg 
Attempting to mount fileshare smb://server.local/ExtHD/munki/repo:
<open file '<stderr>', mode 'w' at 0x10bb1a1e0> Error mounting url "smb://server.local/ExtHD/munki/repo": No route to host, error 65
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1073, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 864, in main
    matchingpkginfo = find_matching_pkginfo(repo, pkginfo)
  File "/usr/local/munki/munkiimport", line 508, in find_matching_pkginfo
    catdb = make_catalog_db(repo)
  File "/usr/local/munki/munkiimport", line 404, in make_catalog_db
    plist = repo.get('catalogs/all')
  File "/usr/local/munki/munkilib/munkirepo/FileRepo.py", line 207, in get
    fileref = open(repo_filepath)
IOError: [Errno 2] No such file or directory: u'/Volumes/ExtHD/munki/repo/catalogs/all'

```

```
air:~ eholtam$ defaults read com.googlecode.munki.munkiimport
{
    "default_catalog" = testing;
    editor = "TextWrangler.app";
    "pkginfo_extension" = ".plist";
    "repo_path" = "/Volumes/repo";
    "repo_url" = "smb://server.local/ExtHD/munki/repo";
}

```

**Comment by poundbangbash** [comment]
Confirmed that https://github.com/munki/munki/commit/da498994170e7d79caadf3aa3e5a0ac1bded1123 addressed this issue.  Closing.
