### ISSUE TITLE
munkiimport (3.0.0.3320) doesn't extract icon to the correct path

### ISSUE THREAD

**Issue by aysiu** [munki/munki#774]
The path is just `icons`:
https://github.com/munki/munki/blob/Munki3/code/client/munkiimport#L256

It used to be a joined path of the munki repo and then the `icons` subdirectory:
https://github.com/munki/munki/blob/master/code/client/munkiimport#L446

With just `icons`, it results in this error:
```
Attempt to create a product icon? [y/n] y
Attempting to extract and upload icon...
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1099, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 1020, in main
    repo, installer_item, pkginfo)
  File "/usr/local/munki/munkiimport", line 205, in generate_png_from_dmg_item
    convert_and_install_icon(repo, pkginfo, icon_path)
  File "/usr/local/munki/munkiimport", line 268, in convert_and_install_icon
    repo.put_from_local_file(repo_png_path, local_png_tmp)
  File "/usr/local/munki/munkilib/munkirepo/FileRepo.py", line 251, in put_from_local_file
    os.makedirs(dir_path, 0755)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Volumes/icons'
```

**Comment by gregneagle** [comment]
That path ('icons') is correct. It sounds like munkiimport doesn't have the right info about your repo.

**Comment by aysiu** [comment]
Probably related to this, then:
https://github.com/munki/munki/issues/773#issuecomment-301224469

**Comment by aysiu** [comment]
Yes, it's related. Not an issue.

**Comment by gregneagle** [comment]
So what caused it?

**Comment by aysiu** [comment]
Didn't have the Repo URL properly configured.
