### ISSUE TITLE
managedsoftwareupdate crashes if the specified manifest doesn't exist

### ISSUE THREAD

**Issue by MagerValp** [munki/munki#814]
Does `get_primary_manifest()` need a few more try/except clauses to handle it a little more gracefully? MSC displays the generic config error dialog when it happens. Which isn't wrong :)

[ManagedSoftwareUpdate.log](https://github.com/munki/munki/files/1414525/ManagedSoftwareUpdate.log)

**Comment by gregneagle** [comment]
I can't reproduce your issue:
```
% sudo ./managedsoftwareupdate 
Managed Software Update Tool
Copyright 2010-2017 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
    Retrieving list of software for this machine...
ERROR: Could not retrieve manifest foobarbaz from the server: HTTP result 404: not found
ERROR: Could not retrieve managed install primary manifest.
Checking Apple Software Update catalog...
	0..20..40..60..80..100
Checking for available Apple Software Updates...
    Finding available software...
    No updates are available.
Finishing...
Done.
```
It looks like the issue you are seeing (which again, I am not) is coming from appleupdates:
`Oct 25 2017 05:18:58 -0700 ERROR: Unexpected error in appleupdates:`

**Comment by erikng** [comment]
I saw a similar trace with munki a few days ago but accidentally deleted the VM before getting the logs. Managedsoftwareupdate crashed if the manifest returned a 403 forbidden.

**Comment by gregneagle** [comment]
If we can't reproduce it we can't verify any potential fix.

**Comment by MagerValp** [comment]
I also nuked the VM unfortunately, let me see if I can recreate it.

**Comment by gregneagle** [comment]
I made a branch with a possible fix, but until we can reproduce the issue and test the change against it I don't want the change in master yet.

**Comment by ejordansc** [comment]
I may be encountering this issue, although I'm seeing a 400 instead of a 403. Does this look familiar?

```
Oct 25 2017 13:31:21 -0700 Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 839, in main
    forcecatalogrefresh=force_catalog_refresh)
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 73, in appleSoftwareUpdatesAvailable
    force_check=forcecheck, suppress_check=suppresscheck)
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 839, in software_updates_available
    count = self.write_appleupdates_file()
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 431, in write_appleupdates_file
    self.client_id, force_refresh=self.force_catalog_refresh)
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 458, in get_primary_manifest_catalogs
    manifest = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 196, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 122, in get_manifest
    raise ManifestNotRetrievedException(err)
ManifestNotRetrievedException: HTTP result 400: bad request
```

If that is indeed the issue, I can reliably reproduce it and would be happy to test against 4cfdddc.

**Comment by homebysix** [comment]
I may be encountering this issue, although I'm seeing a 400 instead of a 403. Does this look familiar?

```
Oct 25 2017 13:31:21 -0700 Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 839, in main
    forcecatalogrefresh=force_catalog_refresh)
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 73, in appleSoftwareUpdatesAvailable
    force_check=forcecheck, suppress_check=suppresscheck)
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 839, in software_updates_available
    count = self.write_appleupdates_file()
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 431, in write_appleupdates_file
    self.client_id, force_refresh=self.force_catalog_refresh)
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 458, in get_primary_manifest_catalogs
    manifest = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 196, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 122, in get_manifest
    raise ManifestNotRetrievedException(err)
ManifestNotRetrievedException: HTTP result 400: bad request
```

If that is indeed the issue, I can reliably reproduce it and would be happy to test against 4cfdddc.

**Comment by gregneagle** [comment]
It might be the same or related. Please test!

**Comment by homebysix** [comment]
Built and installed 4cfdddc on trouble Mac, and the issue was resolved.

I'll try on a couple others to get a sample size > 1.

**Comment by erikng** [comment]
I've been trying to recreate this on my machine but have been unsuccessful.

**Comment by homebysix** [comment]
Sorry to say this was a false alarm. The 400 errors were happening as a result of an authentication issue with our Munki repo, which we fixed separately from my upgrade to the 3.2 branch.

**Comment by gregneagle** [comment]
I'm not sure the _cause_ of your 400 errors is important (from my perspective): what I'm interested in -- does the change in https://github.com/munki/munki/commit/4cfdddcd978a067c7e20510f1142fe45164a591a cause Munki to behave better when things like this happen?

**Comment by homebysix** [comment]
Yes, I suppose. When confronted with the 400 error, Munki 3.1 crashed and 3.2 did not.

**Comment by homebysix** [comment]
Here's the output from Munki 3.1 when it encountered the 400 error:

```
Managed Software Update Tool
Copyright 2010-2017 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
ERROR: Could not retrieve managed install primary manifest.
Checking Apple Software Update catalog...
    Skipping Apple Software Update check because sucatalog is unchanged, installed Apple packages are unchanged and we recently did a full check.
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
ERROR: Unexpected error in appleupdates:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1059, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 839, in main
    forcecatalogrefresh=force_catalog_refresh)
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 73, in appleSoftwareUpdatesAvailable
    force_check=forcecheck, suppress_check=suppresscheck)
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 839, in software_updates_available
    count = self.write_appleupdates_file()
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 431, in write_appleupdates_file
    self.client_id, force_refresh=self.force_catalog_refresh)
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 458, in get_primary_manifest_catalogs
    manifest = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 196, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 122, in get_manifest
    raise ManifestNotRetrievedException(err)
munkilib.updatecheck.manifestutils.ManifestNotRetrievedException: HTTP result 400: bad request
```

And from the new branch on 3.2:

```
Managed Software Update Tool
Copyright 2010-2017 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
ERROR: Could not retrieve managed install primary manifest.
Checking Apple Software Update catalog...
    Skipping Apple Software Update check because sucatalog is unchanged, installed Apple packages are unchanged and we recently did a full check.
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    Retrieving list of software for this machine...
    The following Apple Software Updates are available to install:
        + Safari-11.0
        + iTunes-12.7

Run managedsoftwareupdate --installonly to install the downloaded updates.
Finishing...
Done.
```

Both of these were captured before we resolved our authentication issue and fixed the 400 error. I can re-break it on a test Mac and get more verbose output if it would help.

**Comment by gregneagle** [comment]
I'm going to merge this in Munki3dev. Hope it doesn't break things too much!
