### ISSUE TITLE
Auto-detection of a local Munki repo does not work with manually configured IP address

### ISSUE THREAD

**Issue by sp00l** [munki/munki#854]
I tested this improved auto-detection of a local Munki repo feature 975d2b1f362056ad66d8d998e57d8a6305041a64. If I run `/usr/local/munki/managedsoftwareupdate` I get the following error:
```
Managed Software Update Tool
Copyright 2010-2018 The Munki Project
https://github.com/munki/munki

Starting...
    Looking for local Munki repo server...
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1132, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 856, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 58, in check
    autoconfig.autodetect_repo_url_if_needed()
  File "/usr/local/munki/munkilib/updatecheck/autoconfig.py", line 94, in autodetect_repo_url_if_needed
    detected_url = guess_repo_url()
  File "/usr/local/munki/munkilib/updatecheck/autoconfig.py", line 49, in guess_repo_url
    domain_name = get_domain_name()
  File "/usr/local/munki/munkilib/updatecheck/autoconfig.py", line 39, in get_domain_name
    return dns_config['DomainName']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'DomainName'
```
I discovered, that the `DomainName` key is only set, if the network is configured via DHCP. If you're using manually configured IP addresses, like we have in our company, there is no proper way to set `DomainName` manually. Maybe you can use `SearchDomains` as a backup if the `DomainName` key isn't set.

**Comment by sp00l** [comment]
I think its enough if you just use a safer method to read and if it's not set fall back to the default `http://munki/repo`

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/ff0832fdf376154ea6ec50d6b40a2c7635402333
