### ISSUE TITLE
Traceback if hostname starts with a period

### ISSUE THREAD

**Issue by gmarnin** [munki/munki#859]
I use short hostnames as the manifest name. By accident, I gave the Mac a short hostname and a new manifest that started with a period (.test in this example). On the next Munki run, I got this traceback: 

```
Retrieving list of software for this machine...
	0..20..40..60..80..100
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1132, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 856, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 81, in check
    mainmanifestpath = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 177, in get_primary_manifest
    clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 114, in get_manifest
    manifesturl, manifestpath, message=message)
  File "/usr/local/munki/munkilib/fetch.py", line 425, in munki_resource
    verify=verify)
  File "/usr/local/munki/munkilib/fetch.py", line 378, in getResourceIfChangedAtomically
    message=message, resume=resume, follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 510, in getHTTPfileIfChangedAtomically
    follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 307, in get_url
    os.rename(tempdownloadpath, destinationpath)
OSError: [Errno 21] Is a directory
12mor101m2:~ admin2$ hostname
.test
12mor101m2:~ admin2$ sudo managedsoftwareupdate -V
3.3.1.3537
```

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/27942531049d5df554fb45393f16ea558ef5916c

This bug was triggered only if all of the following was true:
1) hostname starting with a period
2) No manifest with that same name on the server
3) Folder listings enabled for manifests directory on the web server

**Comment by gmarnin** [comment]
I tested the patch which allows munki to find and download site_default 👍
