### ISSUE TITLE
License seat tracking check throws TypeError exception (3.7 Beta 1)

### ISSUE THREAD

**Issue by a-zaleski** [munki/munki#957]
Munki version: 3.7.0.3875
macOS version: 10.14.6 (18G1012)

When testing Munki 3.7 Beta 1 I ran across a change in behavior in the license seat tracking feature after `managedsoftwareupdate` gets a response from the license tracking server (Sal, in this case). Reverting to 3.6.4.3786 allowed for the update check to complete and record the availability of licenses for the software item.

Truncated log:
```
sudo managedsoftwareupdate -vvvv --id=testing

<truncated>

    Headers: {'access-control--methods': 'GET, POST, OPTIONS', 'Content-Type': 'application/xml', <snip>}
    Got: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LicensedItemName</key>
	<true/>
</dict>
</plist>
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 862, in main
    client_id=unicode_or_str(options.id))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 225, in check
    licensing.update_available_license_seats(installinfo)
  File "/usr/local/munki/munkilib/updatecheck/licensing.py", line 75, in update_available_license_seats
    license_dict = FoundationPlist.readPlistFromString(license_data)
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in readPlistFromString
    plistData = NSData.dataWithBytes_length_(data, len(data))
TypeError: Expecting byte-buffer, got str
    Allowing idle sleep
```

**Comment by gregneagle** [comment]
It might take me a while to set up a proper test. Can you test this?
Change line 75 in /usr/local/munki/munkilib/updatecheck/licensing.py from

`license_dict = FoundationPlist.readPlistFromString(license_data)`

to

`license_dict = FoundationPlist.readPlistFromString(license_data.encode('UTF-8'))`

**Comment by a-zaleski** [comment]
The change you described has fixed the issue. 👍
