### ISSUE TITLE
filevault_is_active() fails from type error

### ISSUE THREAD

**Issue by jamesez** [munki/munki#959]
This line in authrestart: https://github.com/munki/munki/blob/5a00d2d39ba9c4384686cd066cd3a27762d02748/code/client/munkilib/authrestart/__init__.py#L42

doesn't convert `exc.output` to a string, so the `'false' in exc.output` fails with a type error.

Traceback:
```Traceback (most recent call last):
  File "/usr/local/munki/munkilib/authrestart/__init__.py", line 41, in filevault_is_active
    active_cmd, stderr=subprocess.STDOUT).decode('UTF-8')
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/fdesetup', 'isactive']' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/munki/munkilib/authrestart/__init__.py", line 43, in filevault_is_active
    if exc.output and 'false' in exc.output:
TypeError: a bytes-like object is required, not 'str'
```

Trivial but probably wrong fix:

`if exc.output and 'false' in exc.output.decode('UTF-8')`

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/91f6087751108df88f1061c3fcbc12897f11ca16 should fix this.
