### ISSUE TITLE
Running makepkginfo on a non-existent file ending in .pkg fails ungracefully

### ISSUE THREAD

**Issue by nmcspadden** [munki/munki#960]
If you run `makepkginfo` on a file path that doesn't exist, but ends in ".pkg", it tries to read it anyway and fails parsing it:
```
$ makepkginfo garbage.pkg
Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 142, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 123, in main
    item = pkginfo['name']
KeyError: 'name'
$ makepkginfo /dev/null.pkg
Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 142, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 123, in main
    item = pkginfo['name']
KeyError: 'name'
```

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/aec2ef70140f5fd5361fdd17f143ac435ecba718
