### ISSUE TITLE
managedsoftwareupdate fails to run after upgrade to 4.0

### ISSUE THREAD

**Issue by workflowsguy** [munki/munki#963]
After the upgrade to Munki 4, `managedsoftwareupdate` no longer works on my iMac.
It keeps failing with
```
Managed Software Update Tool
Copyright 2010-2019 The Munki Project
https://github.com/munki/munki

Starting...
    No CA cert info provided, so nothing to add to System keychain.
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 862, in main
    client_id=unicode_or_str(options.id))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 64, in check
    dummy_keychain_obj = keychain.MunkiKeychain()
  File "/usr/local/munki/munkilib/keychain.py", line 559, in __init__
    add_ca_certs_to_system_keychain()
  File "/usr/local/munki/munkilib/keychain.py", line 179, in add_ca_certs_to_system_keychain
    'No CA cert info provided, so nothing to add to System keychain.')
  File "/usr/local/munki/munkilib/display.py", line 203, in display_debug2
    if prefs.pref('LoggingLevel') > 2:
TypeError: '>' not supported between instances of 'objc.pyobjc_unicode' and 'int'
```

OS: 10.13.6
Managedsoftwareupdate: 4.0.0.3881

**Comment by gregneagle** [comment]
Looks like you’ve set LoggingLevel to a string instead of an integer.

**Comment by gregneagle** [comment]
```
$ python
Python 2.7.16 (default, Oct 16 2019, 00:34:56) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "1" > 1
True
>>> "1" > 2
True
>>> "1" > 3
True
>>> exit()
$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "1" > 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by gregneagle** [comment]
So you can see that Python 2 allowed these comparisons even if the results are a bit unexpected. Python 3 treats this an error. 
Certainly a future release of Munki could throw an `int()` around `prefs.pref('LoggingLevel')` but right now, to address your issue, fix the value for `LoggingLevel`.
