### ISSUE TITLE
Munki 4.0 does not recover gracefully if locally cached file doesn't match hash

### ISSUE THREAD

**Issue by homebysix** [munki/munki#968]
## Summary

Munki does not recover gracefully if a file in the local cache does not match its hash in the repository.

## Steps to reproduce

1. On a Mac that needs an update (or has a pending optional install), ensure the cache is clear.

  ```
  % sudo ls -la /Library/Managed\ Installs/Cache/
  total 0
  drwxr-x---   2 root  admin   64 Dec 26 15:19 .
  drwxr-xr-x  15 root  admin  480 Dec 26 15:19 ..
  ```

2. Initiate a download of the pending update/install, but interrupt the download using Control-C or by disconnecting the network interface.

  ```
  % sudo managedsoftwareupdate -vv                                      
  Managed Software Update Tool
  Copyright 2010-2019 The Munki Project
  https://github.com/munki/munki

  Starting...
      Performing preflight tasks...
      preflight stdout: Using normsus.nordstrom.net as software update server.
      No client cert info provided, so no client keychain will be created.
  Checking for available updates...
  <...snip...>
      * Processing manifest item Xcode for install
      Looking for detail for: Xcode, version latest...
      Considering 14 items with name Xcode from catalog testing
      Considering item Xcode, version 11.3 with minimum os version required 10.14.4
      Our OS version is 10.15.2
      Found Xcode, version 11.3 in catalog testing
      Need to install Xcode
      Downloading Xcode-11.3.dmg from apps/Xcode-11.3.dmg
      Downloading Xcode-11.3.dmg from apps/Xcode-11.3.dmg
      Downloading Xcode-11.3.dmg...
  	0..^CERROR: Unexpected error in updatecheck:
  Traceback (most recent call last):
    File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
      main()
    File "/usr/local/munki/managedsoftwareupdate", line 862, in main
      client_id=unicode_or_str(options.id))
    File "/usr/local/munki/munkilib/updatecheck/core.py", line 289, in check
      is_optional_install=True)
    File "/usr/local/munki/munkilib/updatecheck/analyze.py", line 420, in process_install
      if download.download_installeritem(item_pl, installinfo):
    File "/usr/local/munki/munkilib/updatecheck/download.py", line 185, in download_installeritem
      verify=True)
    File "/usr/local/munki/munkilib/fetch.py", line 440, in munki_resource
      verify=verify)
    File "/usr/local/munki/munkilib/fetch.py", line 393, in getResourceIfChangedAtomically
      message=message, resume=resume, follow_redirects=follow_redirects)
    File "/usr/local/munki/munkilib/fetch.py", line 525, in getHTTPfileIfChangedAtomically
      follow_redirects=follow_redirects)
    File "/usr/local/munki/munkilib/fetch.py", line 257, in get_url
      connection_done = connection.isDone()
    File "/usr/local/munki/munkilib/gurl.py", line 308, in isDone
      NSDate.dateWithTimeIntervalSinceNow_(.1))
  KeyboardInterrupt
  ```

3. Create a fake file at the download destination, to simulate a mismatched hash:

  ```
  % sudo touch /Library/Managed\ Installs/Cache/Xcode-11.3.dmg
  ```

4. Perform another update check and observe that managedsoftwareupdate crashes with an AttributeError.

  ```
  % sudo managedsoftwareupdate -vv                   
  Managed Software Update Tool
  Copyright 2010-2019 The Munki Project
  https://github.com/munki/munki

  Starting...
      Performing preflight tasks...
      preflight stdout: Using normsus.nordstrom.net as software update server.
      No client cert info provided, so no client keychain will be created.
  Checking for available updates...
  <...snip...>
      * Processing manifest item Xcode for install
      Looking for detail for: Xcode, version latest...
      Considering 14 items with name Xcode from catalog testing
      Considering item Xcode, version 11.3 with minimum os version required 10.14.4
      Our OS version is 10.15.2
      Found Xcode, version 11.3 in catalog testing
      Need to install Xcode
      Downloading Xcode-11.3.dmg from apps/Xcode-11.3.dmg
  ERROR: Unexpected error in updatecheck:
  Traceback (most recent call last):
    File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
      main()
    File "/usr/local/munki/managedsoftwareupdate", line 862, in main
      client_id=unicode_or_str(options.id))
    File "/usr/local/munki/munkilib/updatecheck/core.py", line 289, in check
      is_optional_install=True)
    File "/usr/local/munki/munkilib/updatecheck/analyze.py", line 420, in process_install
      if download.download_installeritem(item_pl, installinfo):
    File "/usr/local/munki/munkilib/updatecheck/download.py", line 185, in download_installeritem
      verify=True)
    File "/usr/local/munki/munkilib/fetch.py", line 440, in munki_resource
      verify=verify)
    File "/usr/local/munki/munkilib/fetch.py", line 365, in getResourceIfChangedAtomically
      xattr_hash = getxattr(destinationpath, XATTR_SHA).decode('UTF-8')
  AttributeError: 'NoneType' object has no attribute 'decode'
      Allowing idle sleep
  ```

## Expected behavior

Munki should detect that the downloaded file hash doesn't match the repository, and should re-download the file.

## Versions

```
% sudo pkgutil --pkg-info com.googlecode.munki.core
package-id: com.googlecode.munki.core
version: 4.0.0.3881
volume: /
location: 
install-time: 1577390769
```
```
% managedsoftwareupdate --version
4.0.0.3881
```
```
% /usr/local/munki/python --version
Python 3.7.4
```

**Comment by gregneagle** [comment]
Addressed by #969

**Comment by erikng** [comment]
Any chance this could be issued for a munki 4.0.1 release?

**Comment by gregneagle** [comment]
Yes, it almost certainly will be. You can build a version yourself if you need it now.

**Comment by erikng** [comment]
Stupid question but with the dev branch, if I build that, will the package building code still do proper versioning? I don't want to run into an issue where our versions will not match the official ones.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment]
It will do consistent (“proper”) versioning but there is zero guarantee that whatever version you build will match an official release version.
