### ISSUE TITLE
Big Sur - ImportError: Framework CoreServices could not be found

### ISSUE THREAD

**Issue by macmule** [munki/munki#999]
Logging this for visibility.

```
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 59, in <module>
    from munkilib import appleupdates
  File "/usr/local/munki/munkilib/appleupdates/__init__.py", line 5, in <module>
    from .core import *
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 23, in <module>
    from . import au
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 43, in <module>
    from . import dist
  File "/usr/local/munki/munkilib/appleupdates/dist.py", line 33, in <module>
    from LaunchServices import LSFindApplicationForInfo
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 17, in <module>
    objc.pathForFramework('/System/Library/Frameworks/CoreServices.framework/CoreServices'),
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 122, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 117, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 88, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found
```

**Comment by macmule** [comment]
Simple test:

```
/usr/local/munki/python
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoreServices
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 17, in <module>
    objc.pathForFramework('/System/Library/Frameworks/CoreServices.framework/CoreServices'),
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 122, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 117, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_dyld.py", line 88, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found
```

**Comment by gregneagle** [comment]
It would be helpful if you could reproduce this outside of Munki using the latest PyObjC, and if so, file an issue with the PyObjC maintainers.

**Comment by LcTrKiD** [comment]
Posted in openradar. https://openradar.appspot.com/FB7755688

**Comment by gregneagle** [comment]
I can’t see how this is an Apple bug to fix.

**Comment by LcTrKiD** [comment]
> I can’t see how this is an Apple bug to fix.

For me is a bug, the framework itself is not in its folder. It will always fail no matter the PyObjC version because the file doesn't exist (I didn't try, just guessing)

**Comment by gregneagle** [comment]
But if this is an intentional Apple change, it will be up to the PyObjC devs to make changes to deal with Apple's change.

**Comment by macmule** [comment]
```
sh-3.2# /usr/local/munki/Python.framework/Versions/Current/bin/pip3 install pyobjc
Requirement already satisfied: pyobjc in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreAudioKit==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Photos==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Intents==5.1.2; platform_release >= "16.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreAudio==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-NetworkExtension==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-DVDPlayback==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Automator==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreData==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Quartz==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SceneKit==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SpriteKit==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-VideoSubscriberAccount==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-GameController==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreMedia==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MediaToolbox==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MultipeerConnectivity==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ScriptingBridge==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SearchKit==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-OpenDirectory==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreSpotlight==5.1.2; platform_release >= "17.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-WebKit==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Social==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-StoreKit==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ScreenSaver==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-InputMethodKit==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-VideoToolbox==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-NetFS==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ExceptionHandling==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Network==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-UserNotifications==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Contacts==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MapKit==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-IMServicePlugIn==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-DiscRecording==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Security==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreML==5.1.2; platform_release >= "17.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Collaboration==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-BusinessChat==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CalendarStore==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreBluetooth==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ExternalAccessory==5.1.2; platform_release >= "17.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-core==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MediaPlayer==5.1.2; platform_release >= "16.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Accounts==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Cocoa==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SecurityInterface==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-InstantMessage==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreLocation==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-IOSurface==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CloudKit==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ColorSync==5.1.2; platform_release >= "17.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-EventKit==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CFNetwork==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ModelIO==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-LatentSemanticMapping==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-LaunchServices==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreText==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreWLAN==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreServices==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AdSupport==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-NotificationCenter==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AppleScriptObjC==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CoreMediaIO==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ApplicationServices==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-CryptoTokenKit==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ImageCaptureCore==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ServiceManagement==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-libdispatch==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-PreferencePanes==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AVKit==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-NaturalLanguage==5.1.2; platform_release >= "18.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-Vision==5.1.2; platform_release >= "17.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-FSEvents==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MediaAccessibility==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SystemConfiguration==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-ContactsUI==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-LocalAuthentication==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-DictionaryServices==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-InstallerPlugins==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-iTunesLibrary==5.1.2; platform_release >= "10.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-GameKit==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AVFoundation==5.1.2; platform_release >= "11.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-OSAKit==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-GameCenter==5.1.2; platform_release >= "12.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SyncServices==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SafariServices==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-SecurityFoundation==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-DiskArbitration==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-GameplayKit==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-DiscRecordingUI==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-MediaLibrary==5.1.2; platform_release >= "13.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-PubSub==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-PhotosUI==5.1.2; platform_release >= "15.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AppleScriptKit==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-QTKit==5.1.2; platform_release >= "9.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-AddressBook==5.1.2 in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
Requirement already satisfied: pyobjc-framework-FinderSync==5.1.2; platform_release >= "14.0" in ./Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc) (5.1.2)
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.```

**Comment by gregneagle** [comment]
`.../pip install --upgrade pyobjc`

**Comment by macmule** [comment]
`/usr/local/munki/Python.framework/Versions/Current/bin/pip3 install pyobjc==6.2.1` resulted in the same issue

**Comment by macmule** [comment]
Related - https://github.com/ronaldoussoren/pyobjc/issues/309

**Comment by gregneagle** [comment]
FWIW, Apple's Python2.7+PyObjC works.

Replace the symlink at /usr/local/munki/python with one pointing to /usr/bin/python and that particular traceback goes away.

**Comment by LcTrKiD** [comment]
https://github.com/ronaldoussoren/pyobjc/issues/309#issuecomment-648350096 and this: https://twitter.com/RonaldOussoren/status/1275446083070472194?s=20

**Comment by erikng** [comment]
[munki_python-3.7.4.pkg.zip](https://github.com/munki/munki/files/4864594/munki_python-3.7.4.pkg.zip)

Putting this up as another alternative. I've taken @ronaldoussoren latest change from last week and modified the python munki uses. In our testing this is working pretty well.

**Comment by macmule** [comment]
Awesome.

So, are we likely to see an updated PyObjC included with Munki in a future release?

**Comment by gregneagle** [comment]
I plan to wait until there is an official supported release of PyObjC that works under 10.16/11.0.

If that doesn't look like it will happen before the official Big Sur release, then I'll consider alternate solutions.

**Comment by ronaldoussoren** [comment]
I'll try to push out a bugfix release of PyObjC tomorrows. 

I've spend most of my time on adding full support for macOS 11 in the framework bindings and supporting arm64.

**Comment by macmule** [comment]
Thank you both, @gregneagle & @ronaldoussoren.

Once figured out I can then decide what to do with jamJAR.

**Comment by gregneagle** [comment]
I see https://pyobjc.readthedocs.io/en/latest/changelog.html#version-6-2-2, but I can't yet `pip install` that version. Any hints for an idiot like me, or should I just be patient?

**Comment by gregneagle** [comment]
Looks like it's available via `pip` now!

**Comment by ronaldoussoren** [comment]
Note quite, it's currently uploading.

**Comment by weswhet** [comment]
Just upgraded to 6.2.2 and munki works on BigSur now. Thanks so much, @ronaldoussoren!!!

you too @gregneagle ;)

**Comment by gregneagle** [comment]
The Munki5dev branch contains the changes to build the embedded Python framework with Python 3.8.3 and PyObjC 6.2.2.
https://github.com/munki/munki/commit/37e81f8aaf434146b757aaf445c84586a9cae34a

**Comment by erikng** [comment]
Nice you also bumped to python 3.8.3!

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment]
So now you all get to test to make sure moving to Python 3.8.3 and PyObjC 6.2.2 doesn't cause anything in Munki to break.

**Comment by erikng** [comment]
Unless you were using a deprecated style of code it should be fine, but I do think it's likely that some code will have deprecation warnings that could go away in 3.9/4.
